name: Deploy Frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build dev image
        run: docker build -t mahammadg/docker-react -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true mahammadg/docker-react npm test
